### ISSUE TITLE
ResourceNotFound: turtlebot_gazebo

### ISSUE THREAD

**Issue by q576333** [senthilarul/QLearning-ENPM808X#1]
Hi Guys
Recently, I studying reinforcement learning, so I want implement Q learning algorithm in turtlebot.
I am very appreciate you provide this example, but I face some problem.
I follow your step to run, but I have got this problem :  "ResourceNotFound: turtlebot_gazebo"
How to solve this problem?
Thanks your help.

**Comment by yani-rl-ai** [comment]
did you install the turtlebot?

**Comment by jpalepu** [comment]
you can solve it by adding the dependency. 
sudo apt-get install ros-kinetic-turtlebot-gazebo

**Comment by q576333** [comment]
Thanks for your help, I already solved this problem.
